### ISSUE TITLE
Incomplete Expiry Field Validation

### ISSUE THREAD

**Issue by jperanson** [Beanstream/beanstream-payform#11]
### Expected behaviour:

User should not be able to submit payform for processing if input validation on expiry date fails. The processing button should be disabled if input validation on expiry date fails. 

Related: User should be able to enter expiry in either mm/yyyy or mm/yy format if desired.

### Actual behaviour:

If user enters 2-digit year in expiry, the payform shows "incomplete information" but the user is still able to submit the "incomplete" form for processing. The payform then shows "processing" indefinitely, not returning any response. 

### Steps to reproduce:

Enter expiry date as mm/yy, then "Pay" button on payform.

### Browsers:

All

**Comment by aengusbates** [comment]
Thanks Jonah,

I have reproduced the bug and will put in a fix.

**Comment by aengusbates** [comment]
Fix applied and deployed.
