### ISSUE TITLE
Invalid assumptions in window message event

### ISSUE THREAD

**Issue by littlefyr** [Beanstream/beanstream-payform#26]
I was looking at the demo page in the inspector because I wanted to see what was going on and I was surprised to see a lot of syntax errors being logged. 

The problem arises here at line 112 of beanstream_payform.js

``` javascript
var production;
if (production) {
    // Ensure postmessage came from production
    if (event.origin !== 'https://payform.beanstream.com') {
        return;
    }
}

var obj = JSON.parse(event.data);
```

The problem is that I have a plugin (and I'm going to let that developer know about this) that posts messages to the window so that the associated javascript code knows that the plugin is there. The problem arises because the test for `production` (which I'm guessing becomes truthy in production?) assumes that the event is actually your event. 

More specifically for my situation, it assumes that the value of data is a JSON string, where as this plugin is passing an object. 

Now I suspect that this plugin is not being well behaved but they're relying on you bailing on the mismatched origin values. I would suggest that you should find some other way to identify your events, minimally by wrapping the `JSON.parse` call in a try/catch and bailing if there is an exception, but also if both `obj.type` and `obj.detail` are undefined.

**Comment by aengusbates** [comment]
Hi Adam, thanks for the feedback.

The production variable you identified was an artifact of build/deploy logic recently refactored. I've put in a fix to refactor the domain check inline with MDN's guidelines. This will ensure that Payforms event handlers only  events originating outside Payfom from trigering.
- https://github.com/Beanstream/beanstream-payform/pull/27
- https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

JS syntax is somewhat a matter of taste. This project is using the Google style default in the JSCS linter. I suspect your plugin is just linting against another style guide.
- http://jscs.info/
- https://github.com/Beanstream/beanstream-payform/blob/master/.jscsrc

**Comment by littlefyr** [comment]
I'm not sure this is a syntax issue, to be honest. I was more thinking along the lines of "don't trust what you're given". But if this is going in the iframe, then there is obviously nothing wrong with checking it like you've done in the pull. I wasn't looking at where those lines came from so it didn't think they were all in the iframe.

**Comment by aengusbates** [comment]
Fix live on prod.
