### ISSUE TITLE
Auto clear of card details should be an option

### ISSUE THREAD

**Issue by wingzx3** [Beanstream/beanstream-payform#34]
The payfields on submit clears the form.  This is annoying for the user when on the same form we are submitting billing address for AVS validation.  If the address has a validation error for whatever reason the customer has to re-enter the card data in addition to fixing the address error.

Ideally there would be a way to turn off the auto clearing of the card details.

**Comment by aengusbates** [comment]
There is :)

Load Payfields with the attribute 'data-submitForm'='false' in the script tag. Then manually trigger tokenization by sending Payfields a 'beanstream_payfields_tokenize' event. Payform has to handle the same use case. Take a look at the tokenizationForm object in the repo.

Payfields clears the credit card fields if tokenization is triggered by submit to prevent them from being submitted to the merchant's server.

**Comment by wingzx3** [comment]
Your suggestion does not work.  The fields get cleared regardless of that flag.

I've isolated the problem down to the line
https://github.com/Beanstream/beanstream-payform/blob/master/payfields/assets/js/form/controller.js#L191

I've attached a test case which you can try.
[payfields_clearing_problem.zip](https://github.com/Beanstream/beanstream-payform/files/427614/payfields_clearing_problem.zip)

**Comment by aengusbates** [comment]
Hi Henry,

After tokenisation the fields will get cleared. This is the expected behaviour.

The solution to your problem is to delay tokenization until you have validated other content on your form and you will not need to display the form content to your user any longer.

This is the behaviour in Payform. See the demo: https://payform.beanstream.com/demos/payform/payform.beanstream.com/default.html

Regards,

**Comment by wingzx3** [comment]
Yes. Unfortunately this is not possible because I need to token to create a payment profile on beanstream's side.  However it's during the creation of the payment profile where an validation error can occur.  Such as CVV error or incorrect address format.

**Comment by aengusbates** [comment]
OK, got you. This is a distinct use case that we should be supporting. Reopening issue.

**Comment by aengusbates** [comment]
Removed logic to clear fields. Fix deployed.
