### ISSUE TITLE
card image tiles in payFields

### ISSUE THREAD

**Issue by bowens-bambora** [Beanstream/beanstream-payform#4]
### Expected behaviour:
Card image to appear once.

### Actual behaviour:
Card image (eg. Visa) appears tiled in the PayFields example

### Steps to reproduce:
Launch payFields demo and start typing in a card number to see the image tile across the field.

### Browsers:
Chrome

**Comment by aengusbates** [comment]
Which demo is affected?
I am unable to repro locally or in the hosted demos:
http://localhost:8000/payfields/demos/local.html
http://localhost:8000/payform/demos/local.html
https://s3-us-west-2.amazonaws.com/demos.beanstream.com/payfields/production/index.html
https://s3-us-west-2.amazonaws.com/demos.beanstream.com/payfields/staging/index.html
https://s3-us-west-2.amazonaws.com/demos.beanstream.com/payform/production/default.html
https://s3-us-west-2.amazonaws.com/demos.beanstream.com/payform/staging/default.html

**Comment by aengusbates** [comment]
Bug due to camel casing in folder structure, some local servers are more forgiving than others. I'll rename the relevant folders.

**Comment by aengusbates** [comment]
The commit history above is confusing. The two commits made to Beanstream/beanstream-payform are:
https://github.com/Beanstream/beanstream-payform/commit/778e568df19f5592175ca0daf27d3631340f7690
https://github.com/Beanstream/beanstream-payform/commit/5e0d01d2036d6c1aea197b9eff7027ff880c0685

The first commit deletes folders whose names are camel cased. The second commit re-ads the same folders with the same, but lower cased titles.

**Comment by aengusbates** [comment]
Resolved.
