### ISSUE TITLE
Payfields: IE/Safari displays field errors when submitted with valid values.

### ISSUE THREAD

**Issue by ryanilg** [Beanstream/beanstream-payform#40]
There seems to be an issue specifically with IE and Safari. When you submit the form with valid values, the form is wiped, and the error messages are displayed before/during the ajax request to get the token. It almost seems like the form is submitted twice, first success, then because the form is wiped, it fails.

### Expected behaviour:
Error messages should not be displayed, as the form is valid.

### Actual behaviour:
Error messages are displayed, as the form as been wiped on submit.

### Steps to reproduce:
You can reproduce this using the demo form located at https://s3-us-west-2.amazonaws.com/demos.beanstream.com/payfields/production/index.html.

1. Enter valid Card Number (CC), Expiry, and CVV
2. Submit the form
3. Success message and token displayed but CC field also renders the error "Please enter a credit card number." 

In our use case in our custom app, all 3 fields are displaying an error, not just CC as it is with the demo form. Either way, it should not display any errors as the form has already been submitted successfully.

### Browsers:
IE 11 (11.103), Windows 10 displays the errors on submit.
Safari (9.1.3), OSX Yosemite displays the errors on submit.

FF & Chrome do not display the errors on submit.

Firefox
![firefox](https://cloud.githubusercontent.com/assets/272863/18213712/7ebc9ec4-70fe-11e6-9082-7e88fdef14a0.png)

IE11
![ie11](https://cloud.githubusercontent.com/assets/272863/18213723/87d526d4-70fe-11e6-844f-680fa41b2d92.png)

**Comment by ryanilg** [comment]
Updated ticket, as it seems Safari is having the same issue as IE.

**Comment by aengusbates** [comment]
Thanks for the feedback Ryan,

The bug is because we are clearing the fields on submit, but also validating the input value on change.

**Comment by bowens-bambora** [comment]
Bug resolved and deployed to production.
