### ISSUE TITLE
Payfields: Additional callback before ajax request, after form validation

### ISSUE THREAD

**Issue by ryanilg** [Beanstream/beanstream-payform#41]
It would be great to have an additional callback that is triggered after the form has been validated, but before the ajax request is initialized. The benefit here is a UI element or action could be taken to let the user know we are processing the payment request. The request is not instantaneous, so there is no way to know the request is processing other than looking at the browser, and the fact that the form is wiped.

### Expected behaviour:
A callback is executed when the form is submitted, after it has been checked for validity, before the ajax request is initialized.

### Actual behaviour:
No callback for this exists.

**Comment by aengusbates** [comment]
Good suggestion. I think this eventing would be a useful enhancement.

**Comment by aengusbates** [comment]
Enhancement deployed.
