### ISSUE TITLE
High Risk Scores and CVV Mismatch

### ISSUE THREAD

**Issue by jperanson** [Beanstream/beanstream-payform#42]
### Expected behaviour:
Valid credit cards and CVV's should not be declined
### Actual behaviour:
Risk scores with Payform are extremely high. Up to 94.49 for approved transactions with address and CVV matching. Many transactions are declined with: 
Risk Scores: >95 
CVD Result: CVD Not Provided
Response: Decline (558)

Similar transactions with hosted payform are approved with  low risk scores and CVV match.

### Browsers:

**Comment by bowens-bambora** [comment]
PayForm doesn't do any risk scoring itself. If cards are being declined by the risk scoring then that is in the back end, and possibly with the settings you have in the backoffice. If you send an email to support@beanstream.com we can gladly sort it out for you.
