### ISSUE TITLE
Payform Name Validation Fail in Safari

### ISSUE THREAD

**Issue by jperanson** [Beanstream/beanstream-payform#56]
### Expected behaviour:

Fill in name, email and valid credit card information into popup should allow payment to process
### Actual behaviour:

Payform client-side validation returns error "Please enter your full name"
### Browsers:

Safari Version 9.1.3 (9537.86.7.8)

**Comment by aengusbates** [comment]
Hi Jonah,

What name are you inputting? We are validating on on name being a string longer than 2 chars.

Cheers, A

**Comment by jperanson** [comment]
It's a proper name 7 characters in first name, 7 in last name. This was specific to Safari. The same inputs worked on Chrome.

**Comment by aengusbates** [comment]
What is the name exactly?

**Comment by jperanson** [comment]
It's a customer's name. It passed validation in Chrome.

**Comment by aengusbates** [comment]
Hi Jonah,

I need a string to test to verify the bug. Please send on a list of special chars (non-roman alphabetic chars, punctuation, etc.) from the name, or email the name to support@beanstream.com referencing the Github issue.

Thanks, Aangus

**Comment by aengusbates** [comment]
Closing issue due to insufficient detail. We can reopen issue if detail is added.

**Comment by aengusbates** [comment]
Unable to reproduced in Safari 10.0.1 and IE11,  IE10, Chrome (54), Firefox (48, Opera 41).

Tried to reproduce with strings "aa aa" and "aaaaaaa aaaaaaa".
