### ISSUE TITLE
submitForm="true" fails to append token and run callbacks

### ISSUE THREAD

**Issue by ryanilg** [Beanstream/beanstream-payform#62]
### Expected behaviour:

When submitForm='true' is used, the form should auto submit after the token has been returned, appended to the page, and the beanstream_payfields_tokenUpdated callback has been triggered.

When posted to process.php, the token is supposed to be displayed.
### Actual behaviour:

When submitForm='true' is used, the form is auto submitted, but does not append the token to the page, nor does the beanstream_payfields_tokenUpdated callback get triggered.

When posted to process.php, the token is not displayed, as it was not appended before the form is submitted.
### Steps to reproduce:

I have created 2 examples, both using the same core html, with 2 minor changes, other than some text changes to re-enforce the expected outcome. Both forms post to the same server processing script.
- the value of "submitForm"
- the addition of a manual submit call for manual-submit.php

Uses submitForm=true
http://clients.ryanilg.com/payfields/auto-submit.php

Uses submitForm=false
http://clients.ryanilg.com/payfields/manual-submit.php

If the form is "manually" submitted with submitForm set to false, everything works as expected, the token is returned, appended, and the callback triggers. With the addition of a "submit()" call in the callback, the form can be submitted, where process.php displays the token as expected.
### Browsers:

All

**Comment by aengusbates** [comment]
Thanks Ryan. I'll verify the bug and update the issue.

**Comment by aengusbates** [comment]
This looks like a race condition in the browser. I'm able to reproduce locally using your stripped down demo, but not with the Bootstrap styled demo.

The Payfields script calls form.appendChild() to append the hidden field, then emits the tokenUpdated event and then, if submitForm is true, calls form.submit(). I expected the actions to be completed sequentially, but it looks like the field isn't appended before submit is called.

I'll investigate further.

**Comment by aengusbates** [comment]
The form.appendChild() is calling an API endpoint on the dom that is executing asynchronously. I'll poll the every 5-10 ms checking that the element is appended before progressing the synchronous execution of the js.

I'll add the fix.

**Comment by aengusbates** [comment]
This bug was introduced by in v1.0.5 on 21 Oct 16. We're not preventing default onSubmit. I'll add a fix.

**Comment by aengusbates** [comment]
Fix deployed.
