### ISSUE TITLE
Allow 2-digit expiration years in Payfields

### ISSUE THREAD

**Issue by bmadzar** [Beanstream/beanstream-payform#69]
### Expected behaviour:

Either a 4-year or a 2-year expiration year should be accepted as valid

### Actual behaviour:

Only 4-year expiration years are accepted; the error message is not clear

### Steps to reproduce:

Enter a 2-digit year

### Browsers:

All

### Comments:

We switched from the old tokenization API to Payfields about a month ago. The single biggest issue reported to our CSRs has been that payments don't work. We've traced back to this: many of our customers do not buy things online very often and enter the expiry date exactly as it is on the card. They do not understand the error messages provided.

**Comment by aengusbates** [comment]
Thanks for the feedback Borris. 

Another well reasoned enhancement. There would be no difficulty moving to a 2 digit year. The 4 digit year is just an artifact of Chrome auto-predict's 4 digit year default. I'll loop in the product owner.

**Comment by ryanilg** [comment]
+1.

Based on our findings while logging form errors, the #1 issue is that everyone enters a 2 digit month, and a 2 digit year. Because they do not enter "a valid expiration", they are never able to submit, and we end up with abandoned orders.

**Comment by jasmeet17** [comment]
Fixed in release version [v1.1.0](https://github.com/Beanstream/beanstream-payform/tree/v1.1.0)
