### ISSUE TITLE
PayFields not displaying in IE11 

### ISSUE THREAD

**Issue by Lmasniuk** [Beanstream/beanstream-payform#77]
### Expected behaviour:
Customers attempting to check out on merchant website with IE11 are shown the CC Number, CC Exp, and CVD PayFields. 

### Actual behaviour:
Customers attempting to check out on merchant website with IE11 are not shown the CC Number, CC Exp, and CVD PayFields. Input fields are only sometimes rendered

### Steps to reproduce:

1. An asynchronous script, such as the Facebook Tag API Javascript snippet, needs to exist in the HTML page that is using payfields. 

### Browsers:
IE 9/10/11

**Comment by jasmeet17** [comment]
Fixed in release version [v1.1.0](https://github.com/Beanstream/beanstream-payform/tree/v1.1.0)
