### ISSUE TITLE
Test credit card number fails validation

### ISSUE THREAD

**Issue by michaelaird** [Beanstream/beanstream-payform#80]
### Expected behaviour:

The test credit card numbers provided by beanstream [here](http://www.beanstream.com/boarding/test-card-numbers/) should pass validation.

### Actual behaviour:

The visa card that is limited to $100 (4504481742333) fails validation.

**Comment by aengusbates** [comment]
Thanks for the report.

Bug verified and passed to dev team for resolution.

**Comment by jasmeet17** [comment]
Fixed in release version [v1.1.0](https://github.com/Beanstream/beanstream-payform/tree/v1.1.0)
